remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: raidOffensiveTechnology
description: home to all of our write-ups, research, and resources
